stages: [test, build]
variables:
  GO_VERSION: "1.23"
cache:
  paths: [go/pkg/mod]
test:
  image: golang:${GO_VERSION}
  stage: test
  script:
    - go test ./...
build:
  image: docker:27
  services: [docker:27-dind]
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
