apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project
spec:
  replicas: 2
  selector: {matchLabels: {app: demo-project}}
  template:
    metadata: {labels: {app: demo-project}}
    spec:
      containers:
        - name: demo-project
          image: demo-project:latest
          ports: [{containerPort: 8080}]
          envFrom:
            - configMapRef: {name: demo-project}
            - secretRef: {name: demo-project}
