apiVersion: v1
kind: Secret
metadata: {name: demo-project}
type: Opaque
stringData:
  APP_ENV: replace-me
  DB_HOST: replace-me
  DB_NAME: replace-me
  DB_PASSWORD: replace-me
  DB_PORT: replace-me
  DB_USER: replace-me
  LOG_LEVEL: replace-me
  PORT: replace-me
  REDIS_URL: replace-me
